# Generated by Django 3.0.8 on 2020-11-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_ubi', models.CharField(choices=[('plaza', 'square'), ('e. educativo', 'school'), ('e. medico', 'hospital'), ('e. religioso', 'church'), ('alojamiento', 'lodging'), ('z. comercial', 'shoping_'), ('e. comida', 'restorant')], help_text='elija el tipo de ubicación', max_length=25)),
                ('n_ubi', models.CharField(help_text='como se llama este lugar?', max_length=45)),
                ('direccion', models.CharField(help_text='escriba las calles', max_length=45)),
                ('latit', models.CharField(help_text='ingrese latitud de punto cardinal', max_length=45)),
                ('longi', models.CharField(help_text='introduzca longitud de punto cardinal', max_length=45)),
                ('foto', models.CharField(blank=True, help_text='guarde la foto', max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='e_comida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='ingrese el telefono', max_length=15)),
                ('ubi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion')),
            ],
        ),
    ]
