# Generated by Django 3.0.8 on 2020-12-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_comida',
            name='ubi',
            field=models.OneToOneField(help_text='a que lugar pertenecen estos datos?', on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latit',
            field=models.CharField(help_text='ingrese latitud de punto cardinal', max_length=45, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longi',
            field=models.CharField(help_text='introduzca longitud de punto cardinal', max_length=45, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='n_ubi',
            field=models.CharField(help_text='como se llama este lugar?', max_length=45, verbose_name='nombre de lugar'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='t_ubi',
            field=models.CharField(choices=[('plaza', 'plaza'), ('e. educativo', 'e. educativo'), ('e. medico', 'e. medico'), ('e. religioso', 'e. religioso'), ('alojamiento', 'alojamiento'), ('z. comercial', 'z. comercial'), ('e. comida', 'e. comida')], help_text='elija el tipo de ubicación', max_length=25, verbose_name='tipo de lugar'),
        ),
        migrations.CreateModel(
            name='z_comercial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(help_text='escriba el horario ejm. 06:30 a 15:45', max_length=25, verbose_name='horario')),
                ('ubi', models.OneToOneField(help_text='a que lugar pertenecen estos datos?', on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='e_religioso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relg', models.CharField(help_text='que fe profesa este establecimiento?', max_length=2, verbose_name='religion')),
                ('ubi', models.OneToOneField(help_text='a que lugar pertenecen estos datos?', on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='e_medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telf', models.CharField(help_text='cual es el numero de contacto?', max_length=15, verbose_name='telefono')),
                ('nivel', models.CharField(help_text='indique tipo de consultorio o nivel en caso de hospital', max_length=25, verbose_name='tipo o nivel')),
                ('ubi', models.OneToOneField(help_text='a que lugar pertenecen estos datos?', on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='e_educativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_ini', models.CharField(choices=[('si', 'si'), ('no', 'no')], help_text='el establecimiento tiene nivel inicial?', max_length=2, verbose_name='nivel inicial')),
                ('prim', models.CharField(choices=[('si', 'si'), ('no', 'no')], help_text='el establecimiento tiene nivel primario?', max_length=2, verbose_name='primaria')),
                ('sec', models.CharField(choices=[('si', 'si'), ('no', 'no')], help_text='el establecimiento tiene nivel secundario?', max_length=2, verbose_name='secundaria')),
                ('n_sup', models.CharField(choices=[('si', 'si'), ('no', 'no')], help_text='el establecimiento tiene nivel superior?', max_length=2, verbose_name='nivel superior')),
                ('ubi', models.OneToOneField(help_text='a que lugar pertenecen estos datos?', on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='alojamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telf', models.CharField(help_text='numero telefonico del alojamiento', max_length=15, verbose_name='telefono')),
                ('clas', models.CharField(help_text='que lasificacion tiene ese edificio?', max_length=20, verbose_name='clasificacion')),
                ('ubi', models.OneToOneField(help_text='a que lugar pertenecen estos datos?', on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion')),
            ],
        ),
    ]
