# Generated by Django 3.0.8 on 2020-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20201202_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['id'], 'verbose_name': 'ubicacion', 'verbose_name_plural': 'ubicaciones'},
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='foto',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latit',
            field=models.CharField(max_length=45, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longi',
            field=models.CharField(max_length=45, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='n_ubi',
            field=models.CharField(max_length=45, verbose_name='nombre de lugar'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='t_ubi',
            field=models.CharField(choices=[('plaza', 'plaza'), ('e. comida', 'comida'), ('z. comercial', 'comercial'), ('alojamiento', 'alojamiento'), ('e. educativo', 'educativo'), ('e. medico', 'medico'), ('e. religioso', 'religioso')], max_length=25, verbose_name='tipo de lugar'),
        ),
    ]
