# Generated by Django 3.0.8 on 2021-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20210127_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v_virtual',
            name='url',
            field=models.CharField(help_text='ingrese la url', max_length=512, verbose_name='url'),
        ),
    ]
