# Generated by Django 3.0.8 on 2021-07-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20210127_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.CharField(choices=[('carrusel', 'carrusel'), ('album', 'album'), ('v_virtual', 'v_virtual')], max_length=52, verbose_name='posicion')),
                ('direccion', models.CharField(max_length=45, verbose_name='inserte la imagen')),
                ('url', models.CharField(default='#', max_length=45, verbose_name='a donde redireccionara la imagen')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='escribe una pequeña introduccion')),
                ('leyenda', models.CharField(max_length=150, verbose_name='escribe una pequeña introduccion')),
            ],
        ),
        migrations.DeleteModel(
            name='e_educativo',
        ),
    ]
