# Generated by Django 3.0.8 on 2021-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20210717_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_religioso',
            old_name='relg',
            new_name='relig',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='foto',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='t_ubi',
            field=models.CharField(choices=[('plaza', 'plaza'), ('comida', 'comida'), ('comercial', 'comercial'), ('alojamiento', 'alojamiento'), ('educativo', 'educativo'), ('medico', 'medico'), ('religioso', 'religioso'), ('atractivo', 'atractivo')], max_length=25, verbose_name='tipo de lugar'),
        ),
        migrations.DeleteModel(
            name='z_comercial',
        ),
    ]
