# Generated by Django 3.0.8 on 2021-07-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20210719_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='clas',
            field=models.CharField(help_text='que lasificacion tiene ese edificio?', max_length=45, verbose_name='clasificacion'),
        ),
        migrations.AlterField(
            model_name='e_medico',
            name='nivel',
            field=models.CharField(help_text='indique tipo de consultorio o nivel en caso de hospital', max_length=45, verbose_name='tipo o nivel'),
        ),
        migrations.AlterField(
            model_name='e_religioso',
            name='relig',
            field=models.CharField(help_text='que fe profesa este establecimiento?', max_length=100, verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='t_ubi',
            field=models.CharField(choices=[('plaza', 'plaza'), ('comida', 'comida'), ('comercial', 'comercial'), ('alojamiento', 'alojamiento'), ('educativo', 'educativo'), ('medico', 'medico'), ('religioso', 'religioso'), ('atractivo', 'atractivo'), ('transporte', 'transporte')], max_length=45, verbose_name='tipo de lugar'),
        ),
        migrations.CreateModel(
            name='transporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telf', models.CharField(help_text='cual es el numero de contacto?', max_length=15, verbose_name='telefono')),
                ('tipo', models.CharField(help_text='cual es el tipo de transporte?', max_length=100, verbose_name='tipo')),
                ('ubi', models.OneToOneField(help_text='a que lugar pertenecen estos datos?', on_delete=django.db.models.deletion.CASCADE, to='first.ubicacion')),
            ],
        ),
    ]
