# Generated by Django 3.0.8 on 2021-07-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_auto_20210719_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_comida',
            old_name='phone',
            new_name='telf',
        ),
    ]
