# Generated by Django 3.0.8 on 2021-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_auto_20210722_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_religioso',
            name='telf',
            field=models.CharField(blank=True, help_text='cual es el numero de contacto?', max_length=15, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='telf',
            field=models.CharField(blank=True, help_text='numero telefonico del alojamiento', max_length=15, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='e_comida',
            name='telf',
            field=models.CharField(blank=True, help_text='ingrese el telefono', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='e_medico',
            name='telf',
            field=models.CharField(blank=True, help_text='cual es el numero de contacto?', max_length=15, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='telf',
            field=models.CharField(blank=True, help_text='cual es el numero de contacto?', max_length=15, null=True, verbose_name='telefono'),
        ),
    ]
